### ISSUE TITLE
OOM (8GB VRAM) when attempting run_lora_db_unet_only.sh

### ISSUE THREAD

**Issue by FunWithFaces** [cloneofsimo/lora#124]
I'm starting a new issue here because it looks like this is not necessarily related to the other OOM report.

It was my understanding that unet only training should work with less VRAM, please correct me if I am mistaken on that.

I'm also a bit of a novice with all this so apologies if I am wasting time with a silly problem.

In my understanding the gfx1030_16.kdb issue is just a ROCm thing that can be ignored - this triggers with any use of torch but doesn't normally lead to problems

I'm using the new version pushed today, but never tried this with the old version
----------------------------------------------------------------------------------------------------------------------------

Before training: Unet First Layer lora up tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Before training: Unet First Layer lora down tensor([[-0.2895, -0.1280, -0.1182,  ...,  0.0509, -0.0899,  0.2687],
        [-0.2021, -0.1759, -0.1347,  ...,  0.2454, -0.0814, -0.0840],
        [ 0.0780, -0.2499,  0.1598,  ...,  0.0956,  0.2662,  0.1219],
        [-0.1644, -0.0657, -0.4694,  ..., -0.1089, -0.0435,  0.1429]])
/home/A_User/.local/lib/python3.10/site-packages/diffusers/configuration_utils.py:195: FutureWarning: It is deprecated to pass a pretrained model name or path to `from_config`.If you were trying to load a scheduler, please use <class 'diffusers.schedulers.scheduling_ddpm.DDPMScheduler'>.from_pretrained(...) instead. Otherwise, please make sure to pass a configuration dictionary instead. This functionality will be removed in v1.0.0.
  deprecate("config-passed-as-path", "1.0.0", deprecation_message, standard_warn=False)
***** Running training *****
  Num examples = 5
  Num batches each epoch = 5
  Num Epochs = 600
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 3000
Steps:   0%|                                                                                                                                    | 0/3000 [00:00<?, ?it/s]MIOpen(HIP): Warning [SQLiteBase] Missing system database file: gfx1030_16.kdb Performance may degrade. Please follow instructions to install: https://github.com/ROCmSoftwarePlatform/MIOpen#installing-miopen-kernels-package
Traceback (most recent call last):
  File "/home/A_User/LORA/simotry2/lora/training_scripts/train_lora_dreambooth.py", line 1003, in <module>
    main(args)
  File "/home/A_User/LORA/simotry2/lora/training_scripts/train_lora_dreambooth.py", line 838, in main
    model_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/home/A_User/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/A_User/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 490, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/A_User/.local/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/A_User/.local/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 407, in forward
    sample = upsample_block(
  File "/home/A_User/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/A_User/.local/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 1202, in forward
    hidden_states = resnet(hidden_states, temb)
  File "/home/A_User/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/A_User/.local/lib/python3.10/site-packages/diffusers/models/resnet.py", line 450, in forward
    hidden_states = self.norm1(hidden_states)
  File "/home/A_User/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/A_User/.local/lib/python3.10/site-packages/torch/nn/modules/normalization.py", line 273, in forward
    return F.group_norm(
  File "/home/A_User/.local/lib/python3.10/site-packages/torch/nn/functional.py", line 2528, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
torch.cuda.OutOfMemoryError: HIP out of memory. Tried to allocate 16.00 MiB (GPU 0; 7.98 GiB total capacity; 7.62 GiB already allocated; 266.00 MiB free; 7.66 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_HIP_ALLOC_CONF
Steps:   0%|                                                                                                                                    | 0/3000 [00:16<?, ?it/s]
Traceback (most recent call last):
  File "/home/A_User/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/A_User/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/A_User/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/home/A_User/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/home/A_User/LORA/simotry2/lora/training_scripts/train_lora_dreambooth.py', '--pretrained_model_name_or_path=/home/A_User/LORA/simotry2/lora/SD15', '--instance_data_dir=./data_example_text', '--output_dir=./output_example_lorpt', '--instance_prompt=sks', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=1e-4', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=3000']' returned non-zero exit status 1.

**Comment by FrancescoSaverioZuppichini** [comment]
I have the same error on a 3090 with batch_size = 1
