### ISSUE TITLE
error while using lora_add to create a ckpt file

### ISSUE THREAD

**Issue by oscarnevarezleal** [cloneofsimo/lora#150]
## What happened?

I trained my LoRA using the command below:

```python

PRETRAINED_MODEL="runwayml/stable-diffusion-v1-5" #@param{type: 'string'}
PROMPT="man" #@param{type: 'string'}

STEPS = 1000 #@param {type:"slider", min:0, max:10000, step:10}
BATCH_SIZE = 5 #@param {type:"slider", min:0, max:128, step:1}
FP_16 = True #@param {type:"boolean"}

#@markdown ----
#@markdown UNET PARAMS
LEARNING_RATE = 1e-4 #@param {type:"number"}

#@markdown ----
TRAIN_TEXT_ENCODER = True #@param {type:"boolean"}
#@markdown TEXT ENCODER PARAMS
LEARNING_RATE_TEXT_ENCODER = 5e-5 #@param {type:"number"}

NEW_LEARNING_RATE = LEARNING_RATE / BATCH_SIZE
NEW_LEARNING_RATE_TEXT_ENCODER = LEARNING_RATE_TEXT_ENCODER / BATCH_SIZE

if FP_16:
  fp_16_arg = "fp16"
else:
  fp_16_arg = "no"

command = (f'lora_pti '
             f'--pretrained_model_name_or_path="{PRETRAINED_MODEL}" '
             f'--instance_data_dir="{INSTANCE_DIR}" '
             f'--train_text_encoder '
             f'--output_dir="{OUTPUT_DIR}" '
             f'--instance_prompt="{PROMPT}" '
             f'--resolution=512 '
             f'--use_8bit_adam '
             f'--mixed_precision="{fp_16_arg}" '
             f'--train_batch_size=1 '
             f'--gradient_accumulation_steps=1 '
             f'--lr_scheduler="constant" '
             f'--lr_warmup_steps=0 '
             f'--max_train_steps={STEPS} '
             f'--train_text_encoder '
              '--train_text_encoder'
              '--train_batch_size=1'
              '--gradient_accumulation_steps=4'
              '--scale_lr'
              '--learning_rate_unet=1e-4'
              '--learning_rate_ti=5e-4'
              '--color_jitter'
              '--lr_scheduler=linear'
              '--lr_warmup_steps=0'
              '--placeholder_tokens="<s1>|<s2>"'
              f'--initializer_tokens="{PROMPT}|<rand-0.018>"'
              '--use_template="object"'
              f"--max_train_steps_ti={STEPS}"
              f"--max_train_steps_tuning={STEPS}"
              '--perform_inversion=True'
              '--clip_ti_decay'
              '--save_steps=100'
              '--use_face_segmentation_condition'
              '--resolution=512'
              '--lora_rank=4'
              '--device="cuda:0"'
              '--continue_inversion'
              '--continue_inversion_lr=1e-4'
              '--train_batch_size=1'
             f'--learning_rate_text={NEW_LEARNING_RATE_TEXT_ENCODER}')
```

It works fine, I was testing the results and when decided to merge LoRA safetensor files with original model I executed the command below:

`! lora_add --path_1 runwayml/stable-diffusion-v1-5 --path_2 /content/output/step_1000.safetensors --mode upl-ckpt-v2 --alpha 1.2 --output_path /content/output/merged_model.ckpt`

Then got the following error:

```bash
Lora Add, mode upl-ckpt-v2
Fetching 15 files: 100% 15/15 [00:00<00:00, 37008.56it/s]
Traceback (most recent call last):
  File "/usr/local/bin/lora_add", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/lora_diffusion/cli_lora_add.py", line 118, in main
    fire.Fire(add)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lora_diffusion/cli_lora_add.py", line 96, in add
    weight_apply_lora(loaded_pipeline.unet, torch.load(path_2), alpha=alpha)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x00'.
```

## What was expected?
A CKPT file to be generated for A1111's repo consumption as described [here](https://github.com/cloneofsimo/lora#20221210)

Thank you.

**Comment by cloneofsimo** [comment]
Yeah currently with most recent update to lora_pti that saves using safetensors, and safetensors aren't yet supported to adding with checkpoints. #140 is on the way

**Comment by oscarnevarezleal** [comment]
I'll test [develop](https://github.com/cloneofsimo/lora/tree/develop) in the meantime.
Thank you, @cloneofsimo

**Comment by cloneofsimo** [comment]
All right. this should be possible with the latest update. #140
