### ISSUE TITLE
Since LORA can be applied in the extension and produce target image, but not in webui, I suspect it is something related here, rather than extension malfunction.

### ISSUE THREAD

**Issue by kkiqq22** [cloneofsimo/lora#155]
Since LORA can be applied in the extension and produce target image, but not in webui, I suspect it is something related here, rather than extension malfunction.

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x7fb832ac31f0>]: ValueError
Traceback (most recent call last):
  File "/home/uqwenf/stable-diffusion-webui/modules/extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "/home/uqwenf/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "/home/uqwenf/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 151, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/home/uqwenf/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 89, in load_lora
    key, lora_key = fullkey.split(".", 1)
ValueError: not enough values to unpack (expected 2, got 1)

Steps to reproduce the problem
Select model anything v4.5, Press show extra network.
Select LORA tab, click refresh
Press my LORA file, a prompt lora:A45CGKOTOKA_300:1 shows in prompts section.
(Prompt:lora:A45CGKOTOKA_300:1, masterpiece, best quality,1girl)
Image can be generated but only showing generic waifu, removing lora:A45CGKOTOKA_300:1 shows generic anime waifu

What should have happened?
Generic my target waifu as in "generate sample images" function in dreambooth extension.

**Comment by zanllp** [comment]
same issue
