### ISSUE TITLE
Can't pickle the collate_fn function

### ISSUE THREAD

**Issue by hdeezy** [cloneofsimo/lora#38]
Useful part of the traceback seems to be:
AttributeError: Can't pickle local object 'main.<locals>.collate_fn'

I'm running within the automatic1111 virtual env on windows if that helps.

**Comment by hdeezy** [comment]
Can confirm same issue using anaconda environment I just setup.
Here is how the error goes:


  Using magick windows DLL!
  CUDA SETUP: Loading binary F:\ANACONDA\envs\sd\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
  F:\ANACONDA\envs\sd\lib\site-packages\diffusers\configuration_utils.py:195: FutureWarning: It is deprecated to pass a pretrained model name or path to `from_config`.If you were trying to load a scheduler, please use <class 'diffusers.schedulers.scheduling_ddpm.DDPMScheduler'>.from_pretrained(...) instead. Otherwise, please make sure to pass a configuration dictionary instead. This functionality will be removed in v1.0.0.
    deprecate("config-passed-as-path", "1.0.0", deprecation_message, standard_warn=False)
  ***** Running training *****
    Num examples = 2034
    Num batches each epoch = 509
    Num Epochs = 100
    Instantaneous batch size per device = 4
    Total train batch size (w. parallel, distributed & accumulation) = 4
    Gradient Accumulation steps = 1
    Total optimization steps = 50900
  Steps:   0%|                                                                                 | 0/50900 [00:00<?, ?it/s]Traceback (most recent call last):
    File "C:\Users\<user>\lora\train_lora_dreambooth.py", line 965, in <module>
      main(args)
    File "C:\Users\<user>\lora\train_lora_dreambooth.py", line 791, in main
      for step, batch in enumerate(train_dataloader):
    File "F:\ANACONDA\envs\sd\lib\site-packages\accelerate\data_loader.py", line 372, in __iter__
      dataloader_iter = super().__iter__()
    File "F:\ANACONDA\envs\sd\lib\site-packages\torch\utils\data\dataloader.py", line 444, in __iter__
      return self._get_iterator()
    File "F:\ANACONDA\envs\sd\lib\site-packages\torch\utils\data\dataloader.py", line 390, in _get_iterator
      return _MultiProcessingDataLoaderIter(self)
    File "F:\ANACONDA\envs\sd\lib\site-packages\torch\utils\data\dataloader.py", line 1077, in __init__
      w.start()
    File "F:\ANACONDA\envs\sd\lib\multiprocessing\process.py", line 121, in start
      self._popen = self._Popen(self)
    File "F:\ANACONDA\envs\sd\lib\multiprocessing\context.py", line 224, in _Popen
      return _default_context.get_context().Process._Popen(process_obj)
    File "F:\ANACONDA\envs\sd\lib\multiprocessing\context.py", line 336, in _Popen
      return Popen(process_obj)
    File "F:\ANACONDA\envs\sd\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
      reduction.dump(process_obj, to_child)
    File "F:\ANACONDA\envs\sd\lib\multiprocessing\reduction.py", line 60, in dump
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
      ForkingPickler(file, protocol).dump(obj)
    File "F:\ANACONDA\envs\sd\lib\multiprocessing\spawn.py", line 116, in spawn_main
  AttributeError: Can't pickle local object 'main.<locals>.collate_fn'
      exitcode = _main(fd, parent_sentinel)
    File "F:\ANACONDA\envs\sd\lib\multiprocessing\spawn.py", line 126, in _main
      self = reduction.pickle.load(from_parent)
  EOFError: Ran out of input
  Steps:   0%|                                                                                 | 0/50900 [00:03<?, ?it/s]
  Traceback (most recent call last):
    File "F:\ANACONDA\envs\sd\lib\runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "F:\ANACONDA\envs\sd\lib\runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "F:\ANACONDA\envs\sd\Scripts\accelerate.exe\__main__.py", line 7, in <module>
    File "F:\ANACONDA\envs\sd\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
      args.func(args)
    File "F:\ANACONDA\envs\sd\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
      simple_launcher(args)
    File "F:\ANACONDA\envs\sd\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
      raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

**Comment by hdeezy** [comment]
I tried some things like moving the main function contents under if __name__=="__main__":
as well as moving the collate_fn definition outside of main() with no luck.

**Comment by 78Alpha** [comment]
See here https://github.com/cloneofsimo/lora/issues/4
For a potential fix
