### ISSUE TITLE
AttributeError: Can't pickle local object 'main.<locals>.collate_fn'

### ISSUE THREAD

**Issue by thibaudart** [cloneofsimo/lora#59]
***** Running training *****
  Num examples = 6
  Num batches each epoch = 6
  Num Epochs = 834
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 5000
Steps:   0%|                                                                                                    | 0/5000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:\...\lora\train_lora_w_ti.py", line 1095, in <module>
    main(args)
  File "D:\...\lora\train_lora_w_ti.py", line 901, in main
    for step, batch in enumerate(train_dataloader):
  File "D:\...\venv_diffusers_sd_2\lib\site-packages\accelerate\data_loader.py", line 373, in __iter__
    dataloader_iter = super().__iter__()
  File "D:\...\venv_diffusers_sd_2\lib\site-packages\torch\utils\data\dataloader.py", line 444, in __iter__
    return self._get_iterator()
  File "D:\...\venv_diffusers_sd_2\lib\site-packages\torch\utils\data\dataloader.py", line 390, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\...\venv_diffusers_sd_2\lib\site-packages\torch\utils\data\dataloader.py", line 1077, in __init__
    w.start()
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 224, in _Popen
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 126, in _main
    return _default_context.get_context().Process._Popen(process_obj)
    self = reduction.pickle.load(from_parent)
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 336, in _Popen
EOFError: Ran out of input
    return Popen(process_obj)
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python310\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python310\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.collate_fn'
Steps:   0%|                                                                                                    | 0/5000 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\...\venv_diffusers_sd_2\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\...\venv_diffusers_sd_2\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\...\venv_diffusers_sd_2\lib\site-packages\accelerate\commands\launch.py", line 1069, in launch_command
    simple_launcher(args)
  File "D:\...\venv_diffusers_sd_2\lib\site-packages\accelerate\commands\launch.py", line 551, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\...\\venv_diffusers_sd_2\\Scripts\\python.exe', 'code\\resources\\lora\\train_lora_w_ti.py', '--pretrained_model_name_or_path=models\\SD-2-1-512', '--instance_data_dir=data/instance_images/myboy_512/subject_images', '--output_dir=models_out/lora_512/', '--train_text_encoder', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=5e-5', '--learning_rate_text=5e-5', '--learning_rate_ti=5e-4', '--color_jitter', '--lr_scheduler=constant', '--lr_warmup_steps=100', '--max_train_steps=5000', '--save_steps=500', '--unfreeze_lora_step=2000', '--placeholder_token=<krk>', '--learnable_property=object', '--initializer_token=boy']' returned non-zero exit status 1.

**Comment by thibaudart** [comment]
ok, the line 819 must be remove on windows at least:


        num_workers=1,
